### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by lukeholder** [bnprtr/go-templ-htmx-template#4]
Awesome work Thanks!!

Could we get an example of not just `dev` but building for production and deploying?

**Comment by bnprtr** [comment]
Thanks for the feedback! I just opened #5 that I hope addresses your concerns. Please take a look when you have a chance.

**Comment by lukeholder** [comment]
THANKS! Please keep working on this project. Once I level up I would love to help you work on this. I really think this stack is the future of web dev. Cant stand front end js frameworks.
